platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: latest

inputs:
- name: git-docker-boshrelease
- name: git-docker-ce-release

params:
  ACCESS_KEY_ID:
  SECRET_ACCESS_KEY:

run:
  path: ./git-docker-boshrelease/ci/scripts/update-docker
