builds:
  1673b111b1b2bc455a705fa73a4f0a01fe6f48b8:
    version: 1673b111b1b2bc455a705fa73a4f0a01fe6f48b8
    blobstore_id: ec913b93-b6a2-4f24-527c-6c58df6a8fea
    sha1: 8f6a6c290407b82bae77b19a29d5cf554c9e8ac2
  4780e27e09ac61f569c71bafa1ea7f55ccd3ef73:
    version: 4780e27e09ac61f569c71bafa1ea7f55ccd3ef73
    blobstore_id: 8301cc0e-5f11-4f4b-8d88-cf6356cbd208
    sha1: e9839cea63cd5718f49b75e3ab3181f172cbcb02
  4d8d35003b86ba9496c15ee0911ba46ba2807e0d:
    version: 4d8d35003b86ba9496c15ee0911ba46ba2807e0d
    blobstore_id: 26d069cd-c00f-4546-5a48-143ea54efd09
    sha1: 15b99ad7b84ec2a388aabf847881d219d0d606d8
  65d113cb9a5542ffcf38e5ebc6da290064a956c1a8ba204548c81da76d8bf316:
    version: 65d113cb9a5542ffcf38e5ebc6da290064a956c1a8ba204548c81da76d8bf316
    blobstore_id: 2a5afbbd-737d-478e-4717-9a8eba4b42b3
    sha1: sha256:573cd9b5ff9c6a51849c7b4b77f7c7468a43576f3d0fe21c4aed242b336dd0a8
  696caa44b1a88ac2abc5d6f1575734374fd436b2:
    version: 696caa44b1a88ac2abc5d6f1575734374fd436b2
    blobstore_id: 0c982ffa-e52f-40f1-71c5-0fa177c3d997
    sha1: 00dce0e0122d5b9e135a9cd7d1ca9590f47e381d
  6e072fc1153ccafc1bf307ab173a0b6a249a5e65:
    version: 6e072fc1153ccafc1bf307ab173a0b6a249a5e65
    blobstore_id: c5c37bb5-dccc-4def-47f5-9dac0673e551
    sha1: d911c1f3469ea604d1f5d1aab8f95cc2b4dfd79d
  7e792355e6e9650315b0d2f3547b859c7ea653b859f7d7f52484f39c27a2afb9:
    version: 7e792355e6e9650315b0d2f3547b859c7ea653b859f7d7f52484f39c27a2afb9
    blobstore_id: 5e9bf2a7-1904-4ae6-66d6-e5383a2a378b
    sha1: sha256:7940205d1ad975c69fdb127183658ed87802760a085444c74e61355db13a2713
  8b984db3c0a7a8c4b59e5c7b3a16cda3f473f587:
    version: 8b984db3c0a7a8c4b59e5c7b3a16cda3f473f587
    blobstore_id: cdcbc6fa-27c9-45d7-b3f8-77966d1b9ad8
    sha1: 6425fcabf27dbf4507b7e4478ebe7d383a186c4e
  8d7521e878bfd2f743d5f832be6e0785c15ef2de:
    version: 8d7521e878bfd2f743d5f832be6e0785c15ef2de
    blobstore_id: b119d9ae-8a3b-4821-b8cc-ed7a52a2e452
    sha1: 8bb2bd76d2ff4edcf9e813d0d81f48936dd74a24
  98dddf0a5c30233be5c3a26892fbf954f37c3894:
    version: 98dddf0a5c30233be5c3a26892fbf954f37c3894
    blobstore_id: 5741fa6e-694e-4fd0-8ee5-b559a276e356
    sha1: a26b70fe8d90d058de4a6cba36e6f9ef289f57a9
  bd70dfbbcd499ee00ed36b6f55bc4e96511e0c20:
    version: bd70dfbbcd499ee00ed36b6f55bc4e96511e0c20
    blobstore_id: 628f54df-a3f1-4987-7e91-c41245ecf3a4
    sha1: 22973affdb90600f8cba54264834add710ada121
  be95e0ace0e32f45c6ca0ab89bfbde771f1bc1c2:
    version: be95e0ace0e32f45c6ca0ab89bfbde771f1bc1c2
    blobstore_id: 3732a41f-5f55-479c-7b89-d2c642fbe31e
    sha1: d305b4ef6dc1b68a2d716bd7505fc42f163936d5
  c1d4ea8db4515453b55ddcb2463de63bac485eed:
    version: c1d4ea8db4515453b55ddcb2463de63bac485eed
    blobstore_id: 65caf988-3c58-4dfd-4798-db1aec70d2a9
    sha1: cc38699a9e304abd4d21825380773bddb125a4f7
  c4d13ab492335b0f33bb3dba01fdfa21183af153:
    version: c4d13ab492335b0f33bb3dba01fdfa21183af153
    blobstore_id: 89bfaccb-2f58-46a4-57a3-40e8aff0a567
    sha1: 50ea826ca9aaf023260022a8273e0539d10c3274
  c511b3accf64992a0ac782ad27ad0e5b6e2b1729:
    version: c511b3accf64992a0ac782ad27ad0e5b6e2b1729
    blobstore_id: 362ccccf-186a-4d0d-67ee-7140908f72c9
    sha1: 7e9719cd4f47b534cdb3f08899d36bf59717ee63
  c7a9d60802be9ff97bc689b0fbb5c9543ba2f3ef:
    version: c7a9d60802be9ff97bc689b0fbb5c9543ba2f3ef
    blobstore_id: 15f93aab-caaf-4288-4630-11867573ded3
    sha1: 9c788229f17b8ac9f122d5693648839b499a06cc
  dca9300ff9818d75f623d306d05d7d4aefb8220b:
    version: dca9300ff9818d75f623d306d05d7d4aefb8220b
    blobstore_id: 1f5b3a59-e1ad-4efe-6d9b-da0590837b0f
    sha1: 778975c3e102c02d9035f4026288efce540ce111
  e6d435b1f88cb62e2f550dd3c44bd712fd3c6ccc:
    version: e6d435b1f88cb62e2f550dd3c44bd712fd3c6ccc
    blobstore_id: 7057ec19-46f9-4990-7c87-f6fa54aa1b07
    sha1: 9192384d461ee29ebeb4678a34e1c281341d46cc
  f902b5a256531c279bd287dbe5e868082277642b:
    version: f902b5a256531c279bd287dbe5e868082277642b
    blobstore_id: 4061e21f-aee7-4462-5c40-dcf152399c31
    sha1: 7dde971a3c45b239b8fb9b7560728eaa5f7a7123
format-version: "2"
