builds:
  4780e27e09ac61f569c71bafa1ea7f55ccd3ef73:
    version: 4780e27e09ac61f569c71bafa1ea7f55ccd3ef73
    blobstore_id: 8301cc0e-5f11-4f4b-8d88-cf6356cbd208
    sha1: e9839cea63cd5718f49b75e3ab3181f172cbcb02
  696caa44b1a88ac2abc5d6f1575734374fd436b2:
    version: 696caa44b1a88ac2abc5d6f1575734374fd436b2
    blobstore_id: 0c982ffa-e52f-40f1-71c5-0fa177c3d997
    sha1: 00dce0e0122d5b9e135a9cd7d1ca9590f47e381d
  6e072fc1153ccafc1bf307ab173a0b6a249a5e65:
    version: 6e072fc1153ccafc1bf307ab173a0b6a249a5e65
    blobstore_id: c5c37bb5-dccc-4def-47f5-9dac0673e551
    sha1: d911c1f3469ea604d1f5d1aab8f95cc2b4dfd79d
  8b984db3c0a7a8c4b59e5c7b3a16cda3f473f587:
    version: 8b984db3c0a7a8c4b59e5c7b3a16cda3f473f587
    blobstore_id: cdcbc6fa-27c9-45d7-b3f8-77966d1b9ad8
    sha1: 6425fcabf27dbf4507b7e4478ebe7d383a186c4e
  8d7521e878bfd2f743d5f832be6e0785c15ef2de:
    version: 8d7521e878bfd2f743d5f832be6e0785c15ef2de
    blobstore_id: b119d9ae-8a3b-4821-b8cc-ed7a52a2e452
    sha1: 8bb2bd76d2ff4edcf9e813d0d81f48936dd74a24
  98dddf0a5c30233be5c3a26892fbf954f37c3894:
    version: 98dddf0a5c30233be5c3a26892fbf954f37c3894
    blobstore_id: 5741fa6e-694e-4fd0-8ee5-b559a276e356
    sha1: a26b70fe8d90d058de4a6cba36e6f9ef289f57a9
  be95e0ace0e32f45c6ca0ab89bfbde771f1bc1c2:
    version: be95e0ace0e32f45c6ca0ab89bfbde771f1bc1c2
    blobstore_id: 3732a41f-5f55-479c-7b89-d2c642fbe31e
    sha1: d305b4ef6dc1b68a2d716bd7505fc42f163936d5
  c4d13ab492335b0f33bb3dba01fdfa21183af153:
    version: c4d13ab492335b0f33bb3dba01fdfa21183af153
    blobstore_id: 89bfaccb-2f58-46a4-57a3-40e8aff0a567
    sha1: 50ea826ca9aaf023260022a8273e0539d10c3274
format-version: "2"
