name: docker-swarm
# TODO docker-swarm-sanity-test job

instance_groups:
- name: docker
  instances: 3
  azs: [z1, z2, z3]
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  update: {serial: true}
  jobs:
  - name: docker
    release: docker
    properties:
      tcp_address: 0.0.0.0
      tls_cacert: "((docker-tls.ca))"
      tls_cert: "((docker-tls.certificate))"
      tls_key: "((docker-tls.private_key))"

- name: swarm
  instances: 1
  azs: [z1, z2, z3]
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: swarm-manager
    release: docker

variables:
- name: docker-ca
  type: certificate
  options:
    is_ca: true
    common_name: dockerCA
- name: docker-tls
  type: certificate
  options:
    ca: docker-ca
    common_name: docker
    extended_key_usage:
    - client_auth

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

update:
  canaries: 0
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 32
  serial: false

releases:
- name: docker
  version: 35.1.1
  url: https://github.com/cloudfoundry-incubator/docker-boshrelease/releases/download/v35.1.1/docker-35.1.1.tgz
  sha1: 99271f56d3a5ce151f34f7e518da198afc2738e9
