ctop/ctop-0.5.1-linux-amd64:
  size: 5667856
  object_id: fd5ff7f3-2e78-4efe-4fd9-b043457b063d
  sha: 891ceca493b5dba65b855db09acb1c6d692210ea
docker/aufs-tools_20120411-3_amd64.deb:
  size: 91762
  object_id: c56fabd2-fc6c-4467-911b-5bc0a267f402
  sha: 2dfc1fe386cd3f05ac7e0b4ebcf3ebc8a7f3b04d
docker/autoconf-2.69.tar.gz:
  size: 1927468
  object_id: e5862ef5-142e-486b-b17f-7dd72e7f4a15
  sha: 562471cbcb0dd0fa42a76665acf0dbb68479b78a
docker/bridge-utils-1.5.tar.gz:
  size: 33472
  object_id: 3253d1aa-0846-43b6-a22e-48f7a7905a47
  sha: 1f71b6f22f5d2b6d21e146f4ac20820ad42e58ee
docker/docker-18.06.2-ce.tgz:
  size: 43834194
  object_id: 1d0f0c17-55ea-4ebd-57be-3376720d8aeb
  sha: bdaaad332d598f8a8cdf6c9bddd733eff5ca01f3
flannel/flannel-0.5.5-linux-amd64.tar.gz:
  size: 3489977
  object_id: fee79737-4dad-4420-9f27-3180796bcc4a
  sha: fab60fdf23b029fa39badc008fe951bce5046caa
