ctop/ctop-0.5.1-linux-amd64:
  size: 5667856
  object_id: fd5ff7f3-2e78-4efe-4fd9-b043457b063d
  sha: 891ceca493b5dba65b855db09acb1c6d692210ea
docker/aufs-tools_20120411-3_amd64.deb:
  size: 91762
  object_id: c56fabd2-fc6c-4467-911b-5bc0a267f402
  sha: 2dfc1fe386cd3f05ac7e0b4ebcf3ebc8a7f3b04d
docker/autoconf-2.69.tar.gz:
  size: 1927468
  object_id: e5862ef5-142e-486b-b17f-7dd72e7f4a15
  sha: 562471cbcb0dd0fa42a76665acf0dbb68479b78a
docker/bridge-utils-1.5.tar.gz:
  size: 33472
  object_id: 3253d1aa-0846-43b6-a22e-48f7a7905a47
  sha: 1f71b6f22f5d2b6d21e146f4ac20820ad42e58ee
docker/docker-1.13.1.tgz:
  size: 27851024
  object_id: 2f2af923-48da-4e73-82e1-14f4dedd678e
  sha: 0ff46d8eea0c694f349e1d40cdc10200a1a19e2c
flannel/flannel-0.5.5-linux-amd64.tar.gz:
  size: 3489977
  object_id: fee79737-4dad-4420-9f27-3180796bcc4a
  sha: fab60fdf23b029fa39badc008fe951bce5046caa
golang/go1.5.1.linux-amd64.tar.gz:
  size: 77875767
  object_id: 3c26a347-ae52-4ccb-b0e3-f22e3e863c7c
  sha: 46eecd290d8803887dec718c691cc243f2175fe0
ruby/bundler-1.10.6.gem:
  size: 251392
  object_id: fe11c6d1-bbfe-4865-8687-5010b45fb399
  sha: 55a37fccd1c0cb5542d468e35d3be46dd0667f73
ruby/ruby-2.2.3.tar.gz:
  size: 16626772
  object_id: e4e21c91-1176-4455-b367-097f7bdef1d0
  sha: 0d9e158534cb31e72740138b8f697b57b448e5c3
ruby/rubygems-2.5.0.tgz:
  size: 467978
  object_id: 218484d6-81a4-40e1-b7ca-e720ce3ba3a8
  sha: 03613d7013b61ecabef2424221438a692e53bbfc
ruby/yaml-0.1.6.tar.gz:
  size: 503012
  object_id: c6eb17c4-f0e5-41fe-8114-8a3cb67f6327
  sha: f3d404e11bec3c4efcddfd14c42d46f1aabe0b5d
