name: docker
version: 31.0.1
commit_hash: eec7bfd
uncommitted_changes: false
jobs:
- name: containers
  version: 43423cd82b536388056994753fb29f18d6aaac75
  fingerprint: 43423cd82b536388056994753fb29f18d6aaac75
  sha1: ca3b35f51c7ef0bb75f6fef55abff332cce42dd7
- name: docker
  version: 1673b111b1b2bc455a705fa73a4f0a01fe6f48b8
  fingerprint: 1673b111b1b2bc455a705fa73a4f0a01fe6f48b8
  sha1: 8f6a6c290407b82bae77b19a29d5cf554c9e8ac2
- name: flannel
  version: 0af137c6ac2ea2d131764958dcc0dc7f6d4213ca
  fingerprint: 0af137c6ac2ea2d131764958dcc0dc7f6d4213ca
  sha1: 9e1eca464a6383c8137120d9f1399b4668575401
- name: swarm-agent
  version: 4c839096e6b6f9863d6b60e4441ec97cb7e920a9
  fingerprint: 4c839096e6b6f9863d6b60e4441ec97cb7e920a9
  sha1: 96735d46eae116240bf37c66b8d250bd92162ddc
- name: swarm-manager
  version: de5cfd0c1b266edd537e36077fa6419f8936e7b2
  fingerprint: de5cfd0c1b266edd537e36077fa6419f8936e7b2
  sha1: faa134485086550dd395d59098699e306d0dcac1
packages:
- name: bosh-helpers
  version: a616966453683545eb0e28d88da5a951f5f110ae
  fingerprint: a616966453683545eb0e28d88da5a951f5f110ae
  sha1: c4a69fbee11f7a57875eea3038b12e421ffe5351
  dependencies: []
- name: ctop
  version: e5f579167182e9a1587c2346f4e84bad2c445c2e
  fingerprint: e5f579167182e9a1587c2346f4e84bad2c445c2e
  sha1: e5a38f24fd639f318b8f228959d303aea7f16154
  dependencies: []
- name: docker
  version: 238a6e226d78accc4ca870d3db43e4bfecf4f213
  fingerprint: 238a6e226d78accc4ca870d3db43e4bfecf4f213
  sha1: c65f64c2db39ed39af58278da58c449cd614bc6d
  dependencies: []
- name: flannel
  version: 8d0657c328133f9800822819e2cdcb7eeada2158
  fingerprint: 8d0657c328133f9800822819e2cdcb7eeada2158
  sha1: 4eadaf913d60cae60254ae8540b562e3e6265b0b
  dependencies: []
- name: golang
  version: b8662ebc04e10f6b92d1d9b164130950f9bce214
  fingerprint: b8662ebc04e10f6b92d1d9b164130950f9bce214
  sha1: 4cf8a1a59834401c762741b3de08d0a688f38fb0
  dependencies: []
- name: swarm
  version: 07441eaf60698a19ef83fd3182907bc859cfb836
  fingerprint: 07441eaf60698a19ef83fd3182907bc859cfb836
  sha1: 4fc50b90b059bec2b13ff16196008dc9c4f40136
  dependencies:
  - golang
license:
  version: 3210a836b01ad73b947f585015a88a37cebd9945
  fingerprint: 3210a836b01ad73b947f585015a88a37cebd9945
  sha1: e550d1838cc5f578e23edff53ae1816212efa6e4
