name: docker
version: 35.3.4
commit_hash: 2bf7b28
uncommitted_changes: false
jobs:
- name: containers
  version: 3ec51e4942f709f9a53ca8dc53b9914415044f7a9ff8e69aae93fe0fe5b80eed
  fingerprint: 3ec51e4942f709f9a53ca8dc53b9914415044f7a9ff8e69aae93fe0fe5b80eed
  sha1: sha256:5e6f81900857e459242dc1a21eb77dfb464d70907780ce4e06be94fbee4d6b8d
  packages:
  - bosh-helpers
- name: docker
  version: 7e792355e6e9650315b0d2f3547b859c7ea653b859f7d7f52484f39c27a2afb9
  fingerprint: 7e792355e6e9650315b0d2f3547b859c7ea653b859f7d7f52484f39c27a2afb9
  sha1: sha256:7940205d1ad975c69fdb127183658ed87802760a085444c74e61355db13a2713
  packages:
  - bosh-helpers
  - docker
  - ctop
  - docker-registry-certs
- name: flannel
  version: f372a3e9ab0e8c2892606af8e7710cd2d664e613670ef0a5417933f24f2e66cd
  fingerprint: f372a3e9ab0e8c2892606af8e7710cd2d664e613670ef0a5417933f24f2e66cd
  sha1: sha256:202eca981cb9d10aa6b9516e65e54cde574f315dcfa86dc5d44efc8eb8495aa0
  packages:
  - flannel
- name: sanity-tests
  version: 770227bbad45b0a4c3d94a6e724860555dac08a067d449451c5669daa30935e4
  fingerprint: 770227bbad45b0a4c3d94a6e724860555dac08a067d449451c5669daa30935e4
  sha1: sha256:c8b201cecf3a4c1576561081140a351be357c4e8ddec511084f9446d78bc27b4
  packages:
  - sanity-tests
  - golang-1.12-linux
  - docker
- name: swarm-agent
  version: 17faa48ab8a9941c43e5c886039b39e0c2bee52a9ae59244080515040d12a8c0
  fingerprint: 17faa48ab8a9941c43e5c886039b39e0c2bee52a9ae59244080515040d12a8c0
  sha1: sha256:ecb63a447d7440cadfd1c3b833e2e6d13b22ad2fcaf28717f38071dc0bb7e759
  packages:
  - bosh-helpers
  - swarm
- name: swarm-manager
  version: 0689b5b9a84274d422bd96613bdb59037e14f61eb35c63659fcf07167185f37a
  fingerprint: 0689b5b9a84274d422bd96613bdb59037e14f61eb35c63659fcf07167185f37a
  sha1: sha256:25c827ef2da0219e9a8250b39a18f940da7758438de7caa930e2d627dcd03c04
  packages:
  - bosh-helpers
  - swarm
packages:
- name: bosh-helpers
  version: dd2d29bf5549bea486290eb1fd66881d1b52be16b1f4f770656b44fe9b67663f
  fingerprint: dd2d29bf5549bea486290eb1fd66881d1b52be16b1f4f770656b44fe9b67663f
  sha1: sha256:b36297768d0bf55ad7160bee6e305c49523b7d7ade68c2f0c41224443794e417
  dependencies: []
- name: ctop
  version: 3efa74cd9eda87c329a3cdef5e2a3ba99d655ab04b626b219b99c3afbe2c6bca
  fingerprint: 3efa74cd9eda87c329a3cdef5e2a3ba99d655ab04b626b219b99c3afbe2c6bca
  sha1: sha256:f6e60eb63134f3c8e51a33b9df27f3ecb923c453cadd2ea3d884992a98811057
  dependencies: []
- name: docker
  version: 8848899de1fab40a3a84b1bb9ba9bce2d2bc1712af7944d96ec38bdedf0118ce
  fingerprint: 8848899de1fab40a3a84b1bb9ba9bce2d2bc1712af7944d96ec38bdedf0118ce
  sha1: sha256:8fd8d6ae9c141b6e6bb990e5fd8bfb2b8f52cd55936e01f54aa723b8a4b7e922
  dependencies: []
- name: docker-registry-certs
  version: d15263657941d6628b33d553a234857ad9fd8bfee33b57f17e39f967d66e8322
  fingerprint: d15263657941d6628b33d553a234857ad9fd8bfee33b57f17e39f967d66e8322
  sha1: sha256:6365022e7eee2ea55e6d30c5207cbf151ec32c7de44e79528069d35d1568d73e
  dependencies:
  - golang-1.12-linux
- name: flannel
  version: 1245ea8f6661b63e07c99dfb7fd7eca8fa7169e2c114c294182c40033ee3a71d
  fingerprint: 1245ea8f6661b63e07c99dfb7fd7eca8fa7169e2c114c294182c40033ee3a71d
  sha1: sha256:ce3a4e1eb2f2842b57d77ffcf918d00147847e6882731d0df688eef37fe8c74e
  dependencies: []
- name: golang-1.12-linux
  version: 29fdb6b4cd6c0fe9fb2d8a2a53e89a040ffa33c33f4b9bfae04f5e16060f1f58
  fingerprint: 29fdb6b4cd6c0fe9fb2d8a2a53e89a040ffa33c33f4b9bfae04f5e16060f1f58
  sha1: sha256:2776fe5cdc0068e503e68a977df38f93cf631c8f0125140e4788092cd1f2f663
  dependencies: []
- name: sanity-tests
  version: a44770680e17a719e7b60fe76d6e01945b381a1fdf45a3e7ba045ed1a832823b
  fingerprint: a44770680e17a719e7b60fe76d6e01945b381a1fdf45a3e7ba045ed1a832823b
  sha1: sha256:ef80874642cd7b7aa0acf7a4458addb6fa3fa3456e6c512395d70f9076e1f49d
  dependencies:
  - golang-1.12-linux
- name: swarm
  version: e67042879bf55ff62d649990a005b1d203847a0eedd96b0390c7a32e82855c38
  fingerprint: e67042879bf55ff62d649990a005b1d203847a0eedd96b0390c7a32e82855c38
  sha1: sha256:f168befe730b77e7534750c5bf540730e1c8e5a07408bf53c9a7cb95bb9e0ab7
  dependencies:
  - golang-1.12-linux
license:
  version: 81e3e6d7179fa5024476a96475b7261086329616ef47ee74a404211cddfea4da
  fingerprint: 81e3e6d7179fa5024476a96475b7261086329616ef47ee74a404211cddfea4da
  sha1: sha256:84fa9ab7f75df54387ec025a785db1285a9c52fc67297669ce2ac068495e37f4
