---
- type: replace
  path: /releases/-
  value:
    name: broker-registrar
    version: latest
    # version: 2.0.0
    # url: https://bosh.io/d/github.com/cloudfoundry-community/broker-registrar-boshrelease?v=2.0.0
    # sha1: 83b61f06e43c27845deb59597504e55ee887897e

- type: replace
  path: /releases/-
  value:
    name: routing
    version: 0.147.0
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/cf-routing-release?v=0.147.0
    sha1: 526af8e02a170b424f80148eed95f373bf831a6a

- type: replace
  path: /instance_groups/-
  value:
    name: broker-registrar
    instances: 1
    azs: [z1]
    lifecycle: errand
    vm_type: default
    stemcell: default
    networks: [{name: default}]
    jobs:
    - name: broker-registrar
      release: broker-registrar
      properties:
        cf:
          api_url: ((cf_api_url))
          username: ((cf_admin_username))
          password: ((cf_admin_password))
          skip_ssl_validation: ((cf_skip_ssl_validation))

# - type: replace
#   path: /instance_groups/-
#   value:
#     name: broker-deregistrar
#     instances: 1
#     azs: [z1]
#     lifecycle: errand
#     vm_type: default
#     stemcell: default
#     networks: [{name: default}]
#     jobs:
#     - name: broker-deregistrar
#       release: broker-registrar
