- type: replace
  path: /releases/-
  value:
    name: routing
    version: 0.147.0
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/cf-routing-release?v=0.147.0
    sha1: 526af8e02a170b424f80148eed95f373bf831a6a

- type: replace
  path: /instance_groups/name=docker/jobs/-
  value:
    release: routing
    name: route_registrar
    consumes:
      nats:
        deployment: cf
        from: nats
    properties:
      route_registrar:
        routes:
        - name: ((broker_route_name)) # deployment name
          port: 80
          registration_interval: 20s
          uris: [((broker_route_uri))]

- type: replace
  path: /instance_groups/name=docker/jobs/name=cf-containers-broker/properties/external_host?
  value: ((broker_route_name))
